### ISSUE TITLE
Make more data available? Provide functions to grab arbitrary data?

### ISSUE THREAD

**Issue by jennybc** [jennybc/gapminder#10]
I now see the individual tables are available as Google Sheets (that wasn't always the case)... how can I not do something with this?!?

http://www.gapminder.org/data/

**Comment by hrbrmstr** [comment]
If you'd like I can probably get them all into rdata files and provide a decent function to list and select the data sets

**Comment by jennybc** [comment]
Sure I'd love to start moving on this. The piece I still can't figure out: these sheet are generally no where near "ready to analyze". Would be cool to crowdsource the munging perhaps ...

There are lots of possibilities here.

**Comment by hrbrmstr** [comment]
oh that'd be a neat project (crowdsourcing). pondering what that would look like on my bike ride today 😀

**Comment by jennybc** [comment]
OMG STAT 545 HOMEWORK!!! I can unleash alot of mungers! It's pedagogically sound!

**Comment by jennybc** [comment]
I'm pretty happy with current package scope.
