### ISSUE TITLE
Add the data in various untidy forms?

### ISSUE THREAD

**Issue by jennybc** [jennybc/gapminder#11]
I'm watching @aammd present parts of a new SWC lesson based on Gapminder. Specifically on tidying data. Maybe I should put some untidy versions of this in the package itself? As data.frame or as delimited file?

**Comment by jennybc** [comment]
https://github.com/swcarpentry/r-novice-gapminder

**Comment by dmi3kno** [comment]
We use `gapminder::gapminder` as golden standard and then we fetch other sheets from gapminder website, cleaning them up before joining to original `gapminder` dataset. Those spreadsheets come in wide form with mis-specified column headers and are perfect for practicing some `tidyr::gather`.

What we recently discovered, is that we may not need to ask people to download additional spreadsheets and could use `googlesheets` instead. This [gapminder_datasources.csv](https://github.com/dmi3kno/SWC-tidyverse/blob/master/data/gapminder_datasources.csv) contains `key` column towards the end and can be used for calling `googlesheets::gs_key()`. Not sure if this belongs to package, but I thought someone could find this useful as an idea for trying out data cleaning without leaving R console.

**Comment by jennybc** [comment]
I feel like tidyr probably has this covered with its own datasets.
