### ISSUE TITLE
Can you add a "Cite this package" section in README?

### ISSUE THREAD

**Issue by labarba** [jennybc/gapminder#19]
I see a brief note at the end of the README that says that the package is under CC-BY. I also see under "Releases" that Zenodo integration is turned on. So I assume there is a DOI for this package. 

It would be nice to have the complete citation (with year and DOI), so we don't have to dig around so much (I still don't find the DOI).

Thanks!

**Comment by labarba** [comment]
Thanks for adding the citation info!

I've updated the reference list with the Zenodo DOI here:
http://go.gwu.edu/engcomp2lesson4

**Comment by jennybc** [comment]
Great!

I see you're importing the tsv from a file on python-graph-gallery.com. I suspect that file is a copy of:

https://github.com/jennybc/gapminder/blob/master/inst/extdata/gapminder.tsv

The above is a tsv file that I ship with this package, so it can be used to practice bringing delimited data in from file.

Therefore its content and location is very stable (as well you know now!). Unless you're going to host a copy inside your own teaching space, you're also welcome to import from there. I have been burned in the past with files like this disappearing or moving, which then break my lessons 😣
