### ISSUE TITLE
May I contribute the complete Gapminder data set to your repo?

### ISSUE THREAD

**Issue by jabowery** [jennybc/gapminder#20]
Jenny,

I've written [an "R" script](https://www.dropbox.com/s/3sjcnhcpkp6h349/merge_datapoints.R?dl=1) that joins the entire Gapminder database into [a single csv file](https://www.dropbox.com/s/09sono2oxdn5xzd/all_datapoints.csv.bz2?dl=1), given [the Gapminder github repository](https://github.com/open-numbers/ddf--gapminder--systema_globalis) of said data, which is organized one file per variable.

Since you already have the name "gapminder" in CRAN, would you mind terribly taking ownership of this, the complete, set of Gapminder data?

Thanks!

-- Jim

PS: Let me know how I can be of any further assistance.

**Comment by jennybc** [comment]
If it came in, I'd want to have clean R scripts that show how it is produced from its inputs, as I've done with the small excerpt that's already here. Look in the `data-raw` directory of this repo for that.

Based on the three variables I worked with, there was lots of fussing with inconsistent country names, missing and inconsistent continents, etc. I assume all this is much worse when trying to unify multiple datasets. What's the situation on that front?

What is the final file size of this csv?

Thanks!

**Comment by jabowery** [comment]
Although the file's geography is [ISO_3166-1 alpha 3](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3)-compliant, almost entirely, I'll need to do some "fussing" of my own to get into full compliance.  From there it can be put through conversion to whatever standard you like.  The scripts to do this can be included to build the compliant file directly from Gapminder's github repository.  If necessary it can be an "R" script that calls out to do the `git clone`of that repository.

The problem isn't as bad as it may, at first appear.  Click on the link I gave to the "Gapminder github repository" above.

The `bzip2 -9` size of the data is just above 8M.  The decompressed size is probably misleadingly large because it is very sparse -- rendered even more so by the lack of total compliance with a geo standard.  But you can click on the link I gave for the CSV, download it and bunzip it to see that it takes nearly 160M.

**Comment by jennybc** [comment]
I will look into the feasibility of including such a compressed file. I haven't done so in the past ...

**Comment by jennybc** [comment]
It looks like the dataset *might* be an acceptable size, if included as a compressed R data file. Apparently it's borderline, with 5MB being the current ceiling these days.

So I can't guarantee anything. If you want to pursue it, though, the next step would be a PR with one or more scripts that enact dataset construction and that verify or enforce the consistency of countries/continents, as is done with the current excerpt. Then I'd need to think about how to make it most useful to others, since a data frame with >500 variables is a bit unwieldy.

**Comment by jabowery** [comment]
I'm unfamiliar with what "PR" stands or is for.  

I have filtered out all but rows that are alpha-3 compliant with the R script included below. 

[merge_datapoints.R.gz](https://github.com/jennybc/gapminder/files/1533990/merge_datapoints.R.gz)

 The 8M bz2 of the resulting tsv is at [this link](https://www.dropbox.com/s/uhlmsbrf6zcenqa/all_datapoints.tsv.bz2?dl=1).

  I note [your iso file](https://github.com/jennybc/gapminder/blob/master/data-raw/10_iso-codes.tsv) has 188 country codes.  [The source I used to filter for compliance](https://github.com/mledoze/countries) had 248 in [this json file](https://github.com/mledoze/countries/blob/master/countries.json).  I can construct a country code tsv file congruent with yours if you can tell me the precise names of the json file's fields should be used for your 'country' and 'iso_num' columns.

**Comment by jabowery** [comment]
I've submitted [pull request 21](https://github.com/jennybc/gapminder/pull/21).  Let me know if there is anything I can do to help you evaluate it and/or improve the request.

**Comment by jennybc** [comment]
Thanks @jabowery. I'm about to enter a period of travel. If this falls off my radar, please don't hesitate to ping me here sometime next week.

**Comment by jabowery** [comment]
While you're gone, I'll be putting it through some paces and expect to do some more cleaning.  For instance, I discovered one of the indicators has a name starting with a numeral.

**Comment by jennybc** [comment]
(The country code for North Korea has been fixed, in 003f98f4bfe596a9af5eaa8450b19cd1e570fc87. And I plan to make a release.)

I just touched this repo for the first time in many years, so realistically, I'm going to close remaining issues and PRs, just because it's quite clear that I need to treat this package as "finished". I think it's just going to be a little time capsule.
