### ISSUE TITLE
Documenting the sources of the gapminder data

### ISSUE THREAD

**Issue by friendly** [jennybc/gapminder#23]
First, thanks for providing this dataset for use in R. It is something that I use increasingly for good examples of data vis and data science in my teaching.

I'm writing several different things relating to the `gapminder` data, that originally came from Hans Roslings' site, http://gapminder.org

For stuff only in R, using the variables and the time points you selected, the documentation in the package is sufficient. But it is not sufficient if I want to discuss the historical development of the moving bubble chart and the data available now on http://gapminder.org, or at an earlier stage.

Could you please add a `details` section to the documentation to describe how the current `gapminder` data was derived from the original sources.  e.g., you selected only years 1957--2007, from the ranges
of years that went back to, I think 1807.  If there is an original source file you used, and then selected
just the main variables you've included, you could document that too.

thanks,
-Michael

**Comment by jennybc** [comment]
It is all documented here:

https://github.com/jennybc/gapminder/tree/master/data-raw#readme

We could add a link to that backstory from the help for the main gap minder data frame. Or something along those lines.

**Comment by friendly** [comment]
Yes, that is good for the back story.  You could also, or instead of, add a link to the GitHub repo, where the README gives some of the details I was looking for. Either of these solutions are somewhat unusual for R packages,  but in this case I think it is necessary. 

I love what you've done here (country/continent colors, examples, etc.), but some of this should be exposed in the package documentation.

**Comment by friendly** [comment]
Great! Thx for the follow-up
