### ISSUE TITLE
README figures on CRAN

### ISSUE THREAD

**Issue by IndrajeetPatil** [jennybc/gapminder#24]
Not sure if this has been brought to your attention, but the figures included in `README` look good as GitHub document but appear disproportionately large on `CRAN`:
https://cran.r-project.org/web/packages/gapminder/README.html

**Comment by jennybc** [comment]
Yeah, it's ugly! Next time gapminder updates on CRAN, it _should_ be fixed with some figure-width-controlling code that is already in the setup chunk of the current `README.Rmd`.
