### ISSUE TITLE
country outlines

### ISSUE THREAD

**Issue by dmi3kno** [jennybc/gapminder#25]
I think it would be really cool to have `sf` object with country outlines included in gapminder. Right now we are chasing it in `maptools`, `rnaturalearth` and `spData`. Would be really cool to have gapminder that can be plotted with `geom_sf`. Let me know if you support the idea and would like a PR.

**Comment by jennybc** [comment]
I am pretty ignorant about mapping. In principle, yes, sure I'd be happy to have this. But I would want gapminder to remain an extremely lean little data package. What sort of implementation do you have in mind and how low-impact can it be made in terms of dependencies?

**Comment by dmi3kno** [comment]
I see. Any format we decide to include will be probably too heavy for the package. Lets park this for now. Maybe the best we can do is encourage people to join data to `country_codes` and then use ISO3 to join to any shape file from existing packages (listed in my initial question).
