### ISSUE TITLE
data after 2007

### ISSUE THREAD

**Issue by TonyFly3000** [jennybc/gapminder#26]
Hi, 

May I ask is there any plan on updating the data to 2018 ?  the data on the package is still on 2007

Thank you

**Comment by pachamaltese** [comment]
> No? I think of this package more like an alternative to iris or mtcars: fixed dataset that isn't changing. For use in examples, documentation, and non-perishable teaching materials, that is tremendously helpful.
> 
> That being said, it is sort of sad to watch the dataset grow staler, when I does seem quite natural to add more recent data. As long as the main data frame `gapminder` didn't change, there wouldn't really be a downside to offering a second data frame that changes over time.

Dear Dr. @jennybc 

Thanks a lot for creating this amazing package! After using it for ~3 years, and now with the datos package, I can guarantee it helps people with no previous statistics training to understand how to aggregate and visualize data. In most cases, most of my students are super aware that in Latin America life expectancy has increases and also GDP, so it's really good that they know those facts as they know how their results should look like.

Best,
