### ISSUE TITLE
Facing an issue while loading gapminder.

### ISSUE THREAD

**Issue by akshayparakh25** [jennybc/gapminder#32]
Hello, I am new to R. I wanted to do some data visualization using gapminder datasets. I was able to install it without any issues but I am getting this error while loading the library.
`Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘pillar’
Error: package or namespace load failed for ‘gapminder`

I have tried installing pillar separately as well. There I get following Errors, 
<br>
` Error : object 'glue_collapse' is not exported by 'namespace:glue'
ERROR: lazy loading failed for package 'cli'
 removing 'C:/Users/BabaAkk/Documents/R/win-library/3.3/cli'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.3/bin/x64/R" CMD INSTALL -l "C:\Users\BabaAkk\Documents\R\win-library\3.3" C:\Users\BabaAkk\AppData\Local\Temp\RtmpUFQ9Dg/downloaded_packages/cli_2.0.2.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘cli’ had non-zero exit status
ERROR: dependencies 'cli', 'vctrs' are not available for package 'pillar'
 removing 'C:/Users/BabaAkk/Documents/R/win-library/3.3/pillar'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.3/bin/x64/R" CMD INSTALL -l "C:\Users\BabaAkk\Documents\R\win-library\3.3" C:\Users\BabaAkk\AppData\Local\Temp\RtmpUFQ9Dg/downloaded_packages/pillar_1.4.3.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘pillar’ had non-zero exit status `

Could you please help

**Comment by jennybc** [comment]
This does not sound like a problem specific to the gap minder package, but rather a general Windows package installation problem.

You might have more success straightening it out at https://community.rstudio.com.

Some high-level advice is that, on Windows, one cannot upgrade packages that are currently loaded. And the problems I see above suggest that you've had something like, the tidyverse meta-package loaded, and then tried to install or update lots of other packages, leading to installation failures and perhaps partial installation.

A good thread to consult: https://github.com/rstats-wtf/what-they-forgot/issues/62
