### ISSUE TITLE
Source for the GDP data?

### ISSUE THREAD

**Issue by hail2thief** [jennybc/gapminder#39]
Hello, this is such an amazing resource! I've been hoping to expand the data forward in time and while your documentation is incredibly detailed, it seems due to difficulties with the structure of the GDP data the documentation there is less detailed. Do you remember by chance *which* of the many GDP time series from gapminder you downloaded?

**Comment by jennybc** [comment]
Everything I know is recorded here. If you can't answer your question with this information, then I'm afraid I don't know:

https://github.com/jennybc/gapminder/tree/main/data-raw
