### ISSUE TITLE
Plot circles incorrectly scaled?

### ISSUE THREAD

**Issue by hlapp** [jennybc/gapminder#7]
The `README.Rmd` has this code for a `ggplot2` plot:

```r
ggplot(subset(gapminder, year == 2007 & continent != "Oceania"),
       aes(x = gdpPercap, y = lifeExp)) +
       scale_x_log10(limits = c(150, 115000)) + ylim(c(16, 96)) +
       geom_point(aes(size = sqrt(pop/pi)), pch = 21, color = 'grey20',
       show_guide = FALSE) + scale_size_continuous(range=c(1,40)) +
       facet_wrap(~ continent) + coord_fixed(ratio = 1/43) +
       aes(fill = country) + scale_fill_manual(values = country_colors) +
       theme_bw() + theme(strip.text = element_text(size = rel(1.1)))
```

I think the `aes(size = sqrt(pop/pi))` should be `aes(size = pop)`, and `scale_size_continuous(range=c(1,40))` should be `scale_size_area(max_size=40)`.

Also, `color = 'grey20'` should be unnecessary, shouldn't it?

**Comment by jennybc** [comment]
Re: the size aesthetic: No, this is a deliberate choice to make area scale with population.

Re: the other stuff. You may well be right. I'll take a look.

**Comment by hlapp** [comment]
> Re: the size aesthetic: No, this is a deliberate choice to make area scale with population.

`aes(size=pop) already accomplishes that (according to documentation, and visually, too). Doing it twice over-scales: in your version circles end up with much more than twice the area for twice the population. If you plot the legend for `population` you'll see that.

Here's [an example with scaling fixed as I suggest](https://github.com/Reproducible-Science-Curriculum/rr-organization1/blob/master/files/lit-prog/countryPick4.Rmd). Output is in [this PDF](https://github.com/Reproducible-Science-Curriculum/rr-organization1/blob/master/files/lit-prog/countryPick4.pdf).

**Comment by jennybc** [comment]
OK I stand corrected! I guess this is an artefact of the plot originally being made with base graphics, where the circle size parameter was radius. And I guess I just copied that over to the ggplot2 version w/o too little thought. Thanks for the catch.

**Comment by jennybc** [comment]
This has a surprisingly small impact on how the bubble plot looks.

**Comment by jennybc** [comment]
In fact, I think my original plot was accomplishing the correct thing, but your syntax is better, i.e. `size = pop` and `scale_size_area()`.

**Comment by hlapp** [comment]
It has a big impact in the version of this that's in the Reproducible Science Curriculum, Organization lesson. But that may well be due to other factors.
